export const EVENTS = [
  {
    id: 'ufc-328-chimaev-strickland',
    name: 'UFC 328: Chimaev vs. Strickland',
    location: 'Newark, NJ',
    date: '2026-05-09T18:00:00',
    fights: [
      // MAIN CARD
      {
        id: 'fight_1',
        card: 'main',
        red: 'Khamzat Chimaev',
        blue: 'Sean Strickland',
        redEspn: '#',
        blueEspn: '#',
      },
      {
        id: 'fight_2',
        card: 'main',
        red: 'Tatsuro Taira',
        blue: 'Joshua Van',
        redEspn: '#',
        blueEspn: '#',
      },
      {
        id: 'fight_3',
        card: 'main',
        red: 'Alexander Volkov',
        blue: 'Waldo Cortes Acosta',
        redEspn: '#',
        blueEspn: '#',
      },
      {
        id: 'fight_4',
        card: 'main',
        red: 'Sean Brady',
        blue: 'Joaquin Buckley',
        redEspn: '#',
        blueEspn: '#',
      },
      {
        id: 'fight_5',
        card: 'main',
        red: 'King Green',
        blue: 'Jeremy Stephens',
        redEspn: '#',
        blueEspn: '#',
      },

      // PRELIMS
      {
        id: 'fight_6',
        card: 'prelim',
        red: 'Ateba Gautier',
        blue: 'Ozzy Diaz',
        redEspn: '#',
        blueEspn: '#',
      },
      {
        id: 'fight_7',
        card: 'prelim',
        red: 'Yaroslav Amosov',
        blue: 'Joel Alvarez',
        redEspn: '#',
        blueEspn: '#',
      },
      {
        id: 'fight_8',
        card: 'prelim',
        red: 'Grant Dawson',
        blue: 'Mateusz Rebecki',
        redEspn: '#',
        blueEspn: '#',
      },
      {
        id: 'fight_9',
        card: 'prelim',
        red: 'Jared Gordon',
        blue: 'Jim Miller',
        redEspn: '#',
        blueEspn: '#',
      },
      {
        id: 'fight_10',
        card: 'prelim',
        red: 'Marco Tulio',
        blue: 'Roman Kopylov',
        redEspn: '#',
        blueEspn: '#',
      },
      {
        id: 'fight_11',
        card: 'prelim',
        red: 'Pat Sabatini',
        blue: 'William Gomis',
        redEspn: '#',
        blueEspn: '#',
      },
      {
        id: 'fight_12',
        card: 'prelim',
        red: 'Baisangur Susurkaev',
        blue: 'Djorden Santos',
        redEspn: '#',
        blueEspn: '#',
      },
      {
        id: 'fight_13',
        card: 'prelim',
        red: 'Jose Ochoa',
        blue: 'Clayton Carpenter',
        redEspn: '#',
        blueEspn: '#',
      },
    ],
  },
];
