export const EVENTS = [
  {
    id: 'ufc-327-prochazka-ulberg',
    name: 'UFC 327: Procházka vs. Ulberg',
    location: 'Miami, FL',
    date: '2026-04-11T18:00:00',
    fights: [
      // MAIN CARD
      {
        id: 'fight_1',
        card: 'main',
        red: 'Jiří Procházka',
        blue: 'Carlos Ulberg',
        redEspn: '#',
        blueEspn: '#',
      },
      {
        id: 'fight_2',
        card: 'main',
        red: 'Azamat Murzakanov',
        blue: 'Paulo Costa',
        redEspn: '#',
        blueEspn: '#',
      },
      {
        id: 'fight_3',
        card: 'main',
        red: 'Curtis Blaydes',
        blue: 'Josh Hokit',
        redEspn: '#',
        blueEspn: '#',
      },
      {
        id: 'fight_4',
        card: 'main',
        red: 'Dominick Reyes',
        blue: 'Johnny Walker',
        redEspn: '#',
        blueEspn: '#',
      },
      {
        id: 'fight_5',
        card: 'main',
        red: 'Cub Swanson',
        blue: 'Nate Landwehr',
        redEspn: '#',
        blueEspn: '#',
      },

      // PRELIMS
      {
        id: 'fight_6',
        card: 'prelim',
        red: 'Patricio Pitbull',
        blue: 'Aaron Pico',
        redEspn: '#',
        blueEspn: '#',
      },
      {
        id: 'fight_7',
        card: 'prelim',
        red: 'Mateusz Gamrot',
        blue: 'Esteban Ribovics',
        redEspn: '#',
        blueEspn: '#',
      },
      {
        id: 'fight_8',
        card: 'prelim',
        red: 'Kevin Holland',
        blue: 'Randy Brown',
        redEspn: '#',
        blueEspn: '#',
      },
      {
        id: 'fight_9',
        card: 'prelim',
        red: 'Tatiana Suarez',
        blue: 'Loopy Godinez',
        redEspn: '#',
        blueEspn: '#',
      },
    ],
  },
];
