export const EVENTS = [
  {
    id: 'ufc-fn-adesanya-pyfer',
    name: 'UFC Fight Night: Adesanya vs. Pyfer',
    location: 'Seattle, WA',
    date: '2026-03-28T19:00:00',
    fights: [
      {
        id: 'fight_1',
        red: 'Israel Adesanya',
        blue: 'Joe Pyfer',
        redImage: '/fighters/israel-adesanya.jpg',
        blueImage: '/fighters/joe-pyfer.jpg',
        redEspn: 'https://www.espn.com/mma/fighter/_/id/4285679/israel-adesanya',
        blueEspn: 'https://www.espn.com/mma/fighter/_/id/4684135/joe-pyfer',
      },
      {
        id: 'fight_2',
        red: 'Alexa Grasso',
        blue: 'Maycee Barber',
        redImage: '/fighters/alexa-grasso.jpg',
        blueImage: '/fighters/maycee-barber.jpg',
        redEspn: 'https://www.espn.com/mma/fighter/_/id/3136287/alexa-grasso',
        blueEspn: 'https://www.espn.com/mma/fighter/_/id/4246307/maycee-barber',
      },
      {
        id: 'fight_3',
        red: 'Bryce Mitchell',
        blue: 'Dan Ige',
        redImage: '/fighters/bryce-mitchell.jpg',
        blueImage: '/fighters/dan-ige.jpg',
        redEspn: 'https://www.espn.com/mma/fighter/_/id/3953381/bryce-mitchell',
        blueEspn: 'https://www.espn.com/mma/fighter/_/id/4074001/dan-ige',
      },
      {
        id: 'fight_4',
        red: 'Michel Pereira',
        blue: 'Roman Kopylov',
        redImage: '/fighters/michel-pereira.jpg',
        blueImage: '/fighters/roman-kopylov.jpg',
        redEspn: 'https://www.espn.com/mma/fighter/_/id/4418962/michel-pereira',
        blueEspn: 'https://www.espn.com/mma/fighter/_/id/4300149/roman-kopylov',
      },
      {
        id: 'fight_5',
        red: 'Nassourdine Imavov',
        blue: 'Paulo Costa',
        redImage: '/fighters/nassourdine-imavov.jpg',
        blueImage: '/fighters/paulo-costa.jpg',
        redEspn: 'https://www.espn.com/mma/fighter/_/id/4690539/nassourdine-imavov',
        blueEspn: 'https://www.espn.com/mma/fighter/_/id/4080826/paulo-costa',
      },
    ],
  },

  {
    id: 'ufc-327-prochazka-ulberg',
    name: 'UFC 327: Procházka vs. Ulberg',
    location: 'Las Vegas, NV',
    date: '2026-04-11T19:00:00',
    fights: [
      {
        id: 'fight_1',
        red: 'Jiří Procházka',
        blue: 'Carlos Ulberg',
        redImage: '/fighters/jiri-prochazka.jpg',
        blueImage: '/fighters/carlos-ulberg.jpg',
        redEspn: '#',
        blueEspn: '#',
      },
      {
        id: 'fight_2',
        red: 'Tatsuro Taira',
        blue: 'Joshua Van',
        redImage: '/fighters/tatsuro-taira.jpg',
        blueImage: '/fighters/joshua-van.jpg',
        redEspn: '#',
        blueEspn: '#',
      },
      {
        id: 'fight_3',
        red: 'Mateusz Gamrot',
        blue: 'Benoît Saint Denis',
        redImage: '/fighters/mateusz-gamrot.jpg',
        blueImage: '/fighters/benoit-saint-denis.jpg',
        redEspn: '#',
        blueEspn: '#',
      },
      {
        id: 'fight_4',
        red: 'Amanda Lemos',
        blue: 'Mackenzie Dern',
        redImage: '/fighters/amanda-lemos.jpg',
        blueImage: '/fighters/mackenzie-dern.jpg',
        redEspn: '#',
        blueEspn: '#',
      },
      {
        id: 'fight_5',
        red: 'Geoff Neal',
        blue: 'Ian Machado Garry',
        redImage: '/fighters/geoff-neal.jpg',
        blueImage: '/fighters/ian-garry.jpg',
        redEspn: '#',
        blueEspn: '#',
      },
    ],
  },

  {
    id: 'ufc-fn-burns-malott',
    name: 'UFC Fight Night: Burns vs. Malott',
    location: 'Winnipeg, Canada',
    date: '2026-04-18T18:00:00',
    fights: [
      {
        id: 'fight_1',
        red: 'Gilbert Burns',
        blue: 'Mike Malott',
        redImage: '/fighters/gilbert-burns.jpg',
        blueImage: '/fighters/mike-malott.jpg',
        redEspn: '#',
        blueEspn: '#',
      },
      {
        id: 'fight_2',
        red: 'Charles Jourdain',
        blue: 'Arnold Allen',
        redImage: '/fighters/charles-jourdain.jpg',
        blueImage: '/fighters/arnold-allen.jpg',
        redEspn: '#',
        blueEspn: '#',
      },
      {
        id: 'fight_3',
        red: 'Jasmine Jasudavicius',
        blue: 'Erin Blanchfield',
        redImage: '/fighters/jasmine-jasudavicius.jpg',
        blueImage: '/fighters/erin-blanchfield.jpg',
        redEspn: '#',
        blueEspn: '#',
      },
      {
        id: 'fight_4',
        red: 'Brad Katona',
        blue: 'Raoni Barcelos',
        redImage: '/fighters/brad-katona.jpg',
        blueImage: '/fighters/raoni-barcelos.jpg',
        redEspn: '#',
        blueEspn: '#',
      },
      {
        id: 'fight_5',
        red: 'Marc-Andre Barriault',
        blue: 'Roman Dolidze',
        redImage: '/fighters/marc-andre-barriault.jpg',
        blueImage: '/fighters/roman-dolidze.jpg',
        redEspn: '#',
        blueEspn: '#',
      },
    ],
  },

  {
    id: 'ufc-fn-song-figueiredo',
    name: 'UFC Fight Night: Song vs. Figueiredo',
    location: 'Macau, China',
    date: '2026-05-30T18:00:00',
    fights: [
      {
        id: 'fight_1',
        red: 'Song Yadong',
        blue: 'Deiveson Figueiredo',
        redImage: '/fighters/song-yadong.jpg',
        blueImage: '/fighters/deiveson-figueiredo.jpg',
        redEspn: '#',
        blueEspn: '#',
      },
      {
        id: 'fight_2',
        red: 'Zhang Mingyang',
        blue: 'Alonzo Menifield',
        redImage: '/fighters/zhang-mingyang.jpg',
        blueImage: '/fighters/alonzo-menifield.jpg',
        redEspn: '#',
        blueEspn: '#',
      },
      {
        id: 'fight_3',
        red: 'Sergei Pavlovich',
        blue: 'Jailton Almeida',
        redImage: '/fighters/sergei-pavlovich.jpg',
        blueImage: '/fighters/jailton-almeida.jpg',
        redEspn: '#',
        blueEspn: '#',
      },
      {
        id: 'fight_4',
        red: 'Alex Perez',
        blue: 'Su Mudaerji',
        redImage: '/fighters/alex-perez.jpg',
        blueImage: '/fighters/su-mudaerji.jpg',
        redEspn: '#',
        blueEspn: '#',
      },
      {
        id: 'fight_5',
        red: 'Yan Xiaonan',
        blue: 'Amanda Ribas',
        redImage: '/fighters/yan-xiaonan.jpg',
        blueImage: '/fighters/amanda-ribas.jpg',
        redEspn: '#',
        blueEspn: '#',
      },
    ],
  },
];
